# Generated by Django 6.0.1 on 2026-02-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offers/')),
                ('name', models.CharField(max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
