# Generated by Django 6.0.1 on 2026-02-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
