# Generated by Django 6.0.1 on 2026-02-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_order_status_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
    ]
