# Generated by Django 6.0.1 on 2026-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0006_remove_order_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered')], default='Placed', max_length=20),
        ),
    ]
